import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import datetime
import pandas as pd
from dotenv import load_dotenv

# Ensure we run in the correct directory context so database.py can load Firebase
load_dotenv()
import database

def get_alert_data():
    """Fetch out of stock items and items expiring within 30 days."""
    today = datetime.date.today()
    thirty_days = today + datetime.timedelta(days=30)
    
    # 1. Fetch live inventory
    inventory = database.get_inventory_with_stock()
    
    out_of_stock = []
    for item in inventory:
        stock = item.get("stock", 0)
        if stock <= 0:
            out_of_stock.append(item)
            
    # 2. Check individual batches for precise expiry
    expiring_soon = []
    batches = database.db.collection(database.COLLECTION).stream()
    for doc in batches:
        b = doc.to_dict()
        expiry_str = b.get("expiry_date")
        if expiry_str and expiry_str != "UNKNOWN":
            try:
                exp_date = pd.to_datetime(expiry_str, errors="coerce").date()
                if exp_date is not pd.NaT and exp_date <= thirty_days:
                    # Try to find quantity field
                    qty = b.get("stock") or b.get("Number") or b.get("qty") or b.get("quantity") or 0
                    if int(qty) > 0:  # Only alert if we actually possess the expiring batch
                        b["days_left"] = (exp_date - today).days
                        expiring_soon.append(b)
            except Exception as e:
                pass
                
    # Sort by criticality
    expiring_soon = sorted(expiring_soon, key=lambda x: x.get("days_left", 999))
    
    return out_of_stock, expiring_soon

def generate_html_email(out_of_stock, expiring_soon):
    """Generate a clean HTML report."""
    today_str = datetime.date.today().strftime("%B %d, %Y")
    
    html = f"""
    <html>
      <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #1A2F2B;">
        <div style="background-color: #F4F3ED; padding: 20px; border-radius: 10px;">
            <h2 style="color: #1A2F2B; margin-bottom: 0;">🏥 Pharmacy Daily Report</h2>
            <p style="color: #666; margin-top: 5px;">{today_str}</p>
        </div>
        <br>
    """
    
    if out_of_stock:
        html += """<h3 style="color: #dc2626; border-bottom: 2px solid #fee2e2; padding-bottom: 5px;">🚨 Out of Stock Scanners</h3><ul>"""
        for item in out_of_stock:
            name = item.get("name", "Unknown Product")
            html += f"<li><b>{name}</b> (Reorder immediately)</li>"
        html += "</ul><br>"
    else:
        html += """<h3 style="color: #16a34a;">✅ Inventory Levels Healthy</h3><br>"""
        
    if expiring_soon:
        html += """<h3 style="color: #d97706; border-bottom: 2px solid #fef3c7; padding-bottom: 5px;">⚠️ Expiring within 30 Days</h3><ul>"""
        for b in expiring_soon:
            name = b.get("product_name") or b.get("Name") or "Unknown"
            batch = b.get("batch_number") or b.get("Batch No") or b.get("ID") or "N/A"
            days = b.get("days_left", 0)
            color = "#dc2626" if days < 0 else "#d97706"
            status = f"{abs(days)} days ago" if days < 0 else f"in {days} days"
            html += f"<li><b>{name}</b> (Batch: {batch}) - <span style='color:{color};'>Expires {status}</span></li>"
        html += "</ul>"
    else:
        html += """<h3 style="color: #16a34a;">✅ No Upcoming Expiries</h3><br>"""
        
    html += """
        <br>
        <p style="font-size: 12px; color: #888;">
            This is an automated alert generated by your NovaMed System.<br>
            Please login to the dashboard to take action.
        </p>
      </body>
    </html>
    """
    return html

def send_alert_email():
    out_of_stock, expiring_soon = get_alert_data()
    
    if not out_of_stock and not expiring_soon:
        print("Everything is healthy. No email needed today.")
        return
        
    html_content = generate_html_email(out_of_stock, expiring_soon)
    
    sender_email = os.getenv("SMTP_EMAIL", "pharmacy@example.com")
    sender_password = os.getenv("SMTP_PASSWORD", "")
    receiver_email = os.getenv("ADMIN_EMAIL", "admin@example.com")
    
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"💊 Daily Pharmacy Alerts - {datetime.date.today().strftime('%b %d')}"
    msg["From"] = sender_email
    msg["To"] = receiver_email
    
    part = MIMEText(html_content, "html")
    msg.attach(part)
    
    if not sender_password:
        print("\n[TEST MODE] - No SMTP_PASSWORD in .env.")
        print("Would have sent the following email to:", receiver_email)
        print("-" * 50)
        try:
            print(html_content)
        except UnicodeEncodeError:
            print(html_content.encode("ascii", "ignore").decode("ascii"))
        print("-" * 50)
        return
        
    try:
        # Assuming Gmail SMTP for standard testing. Can be configured.
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        print(f"✅ Successfully sent daily alert email to {receiver_email}")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

if __name__ == "__main__":
    print("Starting Daily Pharmacy Alert Job...")
    send_alert_email()
